### ISSUE TITLE
Baselines results

### ISSUE THREAD

**Issue by seo-95** [facebookresearch/simmc#19]
Baselines result in `mm_action_prediction/README.md` does not match result in the paper. Which are the official baselines result we should refer to?

**Comment by satwikkottur** [comment]
Hello @seo-95 ,

As mentioned just above [here](https://github.com/facebookresearch/simmc/tree/master/mm_action_prediction#installation-same-across-all-sub-tasks), the baseline results in the paper are on a subset of data that is different from these official splits.

Please use the numbers in `mm_action_prediction/README.md` as the official baseline results.
