### ISSUE TITLE
Bug in baseline? (missing sigmoid)

### ISSUE THREAD

**Issue by changjonathanc** [facebookresearch/simmc#21]
https://github.com/facebookresearch/simmc/blob/9308dc2dd749665c59a28043c72aace45f3d96b5/mm_action_prediction/models/action_executor.py#L215

This is a multi-label prediction, so there should be a sigmoid. (or simply change 0.5 to 0)
I tried it and the Action Attribute Accuracy increased from 54.79 to 56.06.
Will the code and score in readme be updated?

**Comment by satwikkottur** [comment]
Hello @cccntu ,

Thanks for finding this. I'll add the sigmoid, retrain the baselines for Fashion, and update the scores.
