### ISSUE TITLE
Missing dialogue_task_id in training

### ISSUE THREAD

**Issue by seo-95** [facebookresearch/simmc#3]
By analyzing the file `fashion_train_dials.json` I have found some missing `dialogue_task_id` keys in the following dialogues:

```
id: 3406 ; is dialogue_task_id missing: True
id: 3969 ; is dialogue_task_id missing: True
id: 4847 ; is dialogue_task_id missing: True
id: 321 ; is dialogue_task_id missing: True
id: 3455 ; is dialogue_task_id missing: True
id: 3414 ; is dialogue_task_id missing: True
```

**Comment by satwikkottur** [comment]
Hello @seayoung1112 ,

Thanks for raising this. We've noticed the same issue at our end as well. Since this contributes towards <0.1% of the data, feel free to ignore these dialogs.

Thanks!

**Comment by seo-95** [comment]
> Hello @seayoung1112 ,
> 
> Thanks for raising this. We've noticed the same issue at our end as well. Since this contributes towards <0.1% of the data, feel free to ignore these dialogs.
> 
> Thanks!

Thanks for the reply. Is there anyway a description of what `dialogue_task_id` field represents?

**Comment by shanemoon** [comment]
Hi @seo-95, thank you for your comments. `dialog_task_id` defines the dialog scenario for the SIMMC-Fashion dialog collection. 

During the dialog collection for SIMMC-Fashion, the assistant-playing annotators were presented with a total of 10 images, where their `image_id`s were defined by `dialog_task_id` of each dialog (A random `dialog_task_id` was chosen for each new dialog that was collected). This information (a set of item retrieval candidates) can be used for the MM-Action Prediction subtask -- more details will be announced soon. We will make sure we post here again as well. Thank you very much!
