### ISSUE TITLE
Question about Fashion attributes

### ISSUE THREAD

**Issue by billkunghappy** [facebookresearch/simmc#31]
Hi
I have some questions about the attribute value of fashion dataset.
I was using the "fashion_devtest_dials_api_calls.json" made by the preprocessing scripts of the mm_action_prediciton
When I look into it, I found some weird attribute values.

In the attribute vocabulary and action_evaluation.py, I've found that there exist 6 available attributes and 8 ignored attributes.
However, in the "fashion_devtest_dials_api_calls.json" file, I have found 27 kinds of attribute values.
available attributes: 
`
["availableSizes", "brand", "color", "customerRating", "info", "other", "price"]
`
ignored attributes:
`["minPrice", "maxPrice","furniture_id", "material", "decorStyle", "intendedRoom","raw_matches","focus"]`
Founded attributes:
`
['soldBy', 'pattern', 'clothingStyle', 'waistStyle', 'price', 'forOccasion', 'skirtLength', 'clothingCategory', 'customerRating', 'necklineStyle', 'color', 'embellishment', 'size', 'jacketStyle', 'material', 'info', 'ageRange', 'sleeveLength', 'hemLength', 'sweaterStyle', 'dressStyle', 'amountInStock', 'availableSizes', 'sleeveStyle', 'skirtStyle', 'hemStyle', 'brand']
`
What are those founded attributes which are neither available attributes nor ignored attributes?
Should we just ignore them and delete them when training?
And will these attributes be ignored by the **action_evaluation.py** script?

**Comment by satwikkottur** [comment]
Hello @billkunghappy,

Could you take a look at this PR (https://github.com/facebookresearch/simmc/pull/22) and see if that discussion helps? Feel free to re-open the issue if this does not clarify.
