### ISSUE TITLE
Arguments values for Action Prediction task

### ISSUE THREAD

**Issue by seo-95** [facebookresearch/simmc#8]
Hi!
I used the `mm_action_prediction/tools/extract_actions_fashion.py` and I have found the following values that API arguments can assume:

`{'DA:INFORM:GET:SWEATER', 'hemStyle', 'warmthRating', 'size', 'ageRange', 'info', 'material', 'clothingCategory', 'brand', 'DA:ASK:GET:JACKET', 'skirtLength', 'dressStyle', 'waistStyle', 'waterResistance', 'DA:ASK:CHECK:SWEATER', 'color', 'customerRating', 'DA:INFORM:GET:CLOTHING', 'hasPart', 'sequential', 'forGender', 'price', 'availableSizes', 'DA:INFORM:GET:JACKET', 'DA:ASK:GET:CLOTHING', 'skirtStyle', 'sleeveLength', 'pattern', 'sleeveStyle', 'DA:ASK:GET:SKIRT', 'DA:ASK:GET:SWEATER', 'necklineStyle', 'jacketStyle', 'soldBy', 'embellishment', 'madeIn', 'sweaterStyle', 'clothingStyle', 'hemLength', 'DA:ASK:CHECK:CLOTHING', 'DA:ASK:GET:DRESS', 'DA:INFORM:GET:SKIRT', 'amountInStock', 'forOccasion', 'DA:INFORM:GET:DRESS'}`

There are two questions I want to ask you:

1. Is it ok to have DA:INFORM:GET:SWEATER (and all the others DIALOGUE_ACT:ACTIVITY:OBJECT) as argument value for an API or there is an error during the generation?

2. Do we have a list of possible values that the arguments can assume for each API? In Table 4 of the paper we have a list of possible values terminating with "etc.".

Thank you

**Comment by satwikkottur** [comment]
Hello @seo-95,

Thanks for flagging this. Ideally, no intent value should show up here. Will look into this and get back soon.

**Comment by seo-95** [comment]
Thank you @satwikkottur for the fast response. Can you please provide an answer also for the second question:

Do we have a shape for each API? I mean, a list of the types of arguments a certain API (e.g., SpecifyInfo) can take?
